package com.fanyiadrien.ictu_ex.data.model

/**
 * Represents a marketplace listing stored in Firestore.
 *
 * Collection: "listings"
 * Document ID: Auto-generated by Firestore
 */
data class Listing(
    val id: String = "",
    val sellerId: String = "",
    val sellerStudentId: String = "",
    val title: String = "",
    val description: String = "",
    val price: Double = 0.0,
    val imageUrl: String = "",
    val category: String = "",        // matches ListingCategory.displayName
    val available: Boolean = true,
    val createdAt: Long = 0L
)